#pragma config(Motor,  port2,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           R1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           R2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           B1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           I1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           S1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           S2,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[L1] = vexRT[Ch3];
		motor[L2] = vexRT[Ch3];
		motor[R1] = vexRT[Ch2];
		motor[R2] = vexRT[Ch2];
		motor[B1] = vexRT[Ch3 / 4];
		motor[B1] = vexRT[Ch2 / 2];
		if(vexRT[Btn5U] == 1)
		{
			motor[I1] = 127;
		}
		if(vexRT[Btn5D] == 1)
		{
			motor[I1] = 0;
		}
		if(vexRT[Btn6D] == 1)
		{
			motor[S1] = 0;
			motor[S2] = 0;
		}
		if(vexRT[Btn6U] == 1)
		{
			motor[S1] = 127;
			motor[S2] = 127;
		}
		if(vexRT[Btn8R] == 1)
		{
			motor[L1] = 127;
			motor[L2] = 127;
			motor[R1] = -127;
			motor[R2] = -127;
		}
		if(vexRT[Btn7L] == 1)
		{
			motor[L1] = -127;
			motor[L2] = -127;
			motor[R1] = 127;
			motor[R2] = 127;
		}
	}
}
