#pragma config(Motor,  port1,           LU,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LD,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RD,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RU,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Lift,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	int shooterspeed;
	shooterspeed = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//Main Drive
	  motor[LU] = vexRT[Ch1];
	  motor[LD] = vexRT[Ch1];
	  motor[RD] = vexRT[Ch3];
	  motor[RU] = vexRT[Ch3];
	  motor[LU] = vexRT[Btn5D];
	  //Lift and Shooter
	  if(vexRT[Btn5D] == 1)
	  {
	  	int shooterspeed;
	  	shooterspeed = shooterspeed + 1;
	  }
	  if(vexRT[Btn5D] == 1)
	  {
	  	motor[Lift] = 127;
	}
	  if(vexRT[Btn5U] == 1)
	  {
	  	motor[Lift] = 0;
}
	}
}
