#pragma config(Motor,  port2,           righttop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightbottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lefttop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftbottom,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1==1)
motor(righttop)=vexRT[Ch2];
motor(rightbottom)=vexRT[Ch2];
motor(lefttop)=vexRT[Ch2];
motor(leftbottom)=vexRT[Ch2];
motor(lift1)=vexRT[Ch2];

}
