#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftencoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           righttop,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightbottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lefttop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftbottom,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           hang,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//LCD Display code.
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
//Declare count variable to keep track of our choice
int count = 0;
//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release----------------------------------1--------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

//

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void TurnLeft()
{
	motor[leftbottom] = -127;
	motor[rightbottom] = 127;
	motor[righttop] = 127;
	motor[lefttop] = -127;
}
void TurnRight()
{
	motor[leftbottom] = 127;
	motor[rightbottom] = -127;
	motor[righttop] = -127;
	motor[lefttop] = 127;
}
void MoveForward()
{
	motor[leftbottom] = 127;
	motor[rightbottom] = 127;
	motor[righttop] = 127;
	motor[lefttop] = 127;
}
void MoveBackward()
{
	motor[leftbottom] = -127;
	motor[rightbottom] = -127;
	motor[righttop] = -127;
	motor[lefttop] = -127;
}
void StopMoving()
{
	motor[leftbottom] = 0;
	motor[rightbottom] = 0;
	motor[righttop] = 0;
	motor[lefttop] = 0;
}
void pre_auton()
{

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Left Time");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Right Time");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Left Encoders");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Right Encoders");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:

			count = 0;

			break;

		}
	}

}
task encoders(){
	SensorValue(rightencoder) = 0;
	SensorValue(leftencoder) = 0;
	int rightencoder = SensorValue(rightencoder);
	int leftencoder = SensorValue(leftencoder);
	while (1){
	rightencoder = SensorValue(rightencoder);
	leftencoder = SensorValue(leftencoder);
}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	startTask(encoders);
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Left Time");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(20);						// Robot waits for 20 milliseconds
		MoveForward();
		motor[hang] = 127;
		motor[lift1] = 127;
		motor[lift2] = 127;
		wait1Msec(800);
		//Move Forward .8 Secconds
		//Step 1: Move out of starting square
		motor[lift1] = 40;
		motor[lift2] = 40;
		TurnLeft();
		wait1Msec(375);
		//Rotate Right .45 Secconds
		MoveForward();
		motor[claw] = 127;
		wait1Msec(450);
		//Move Forward .35 Secconds
		TurnRight();
		motor[claw] = 0;
		wait1Msec(400);
		//Rotate Left .45 Secconds
		//Step 2: Rotate and move into position to knock stars off fence
		StopMoving();
		motor[lift1] = 50;
		motor[lift2] = 50;
		wait1Msec(300);
		//Raise Lift and Open Claw .3 Secconds
		MoveForward();
		wait1Msec(1300);
		//Move Forward 1.3 Secconds
		//Step 3: Knock stars off of fence
		motor[lift1] = 10;
		motor[lift2] = 10;
		motor[claw] = 0;
		motor[hang] = 0;
		MoveForward();
		wait1Msec(300);
		//NEXT TASK: Get cube to other side
		MoveBackward();
		wait1Msec(1080);
		//Move Backwards 10.8 Secconds
		//Step 1: Move into position
		TurnRight();
		motor[lift1] = -127;
		motor[lift2] = -127;
		wait1Msec(700);
		//Rotate Left .75 Secconds
		motor[claw] = 0;
		motor[leftbottom] = 127;
		motor[lefttop] = 127;
		motor[rightbottom] = 127;
		motor[righttop] = 127;
		wait1Msec(550);
		//Move Forwards .55 Secconds
		motor[claw] = 127;
		wait1Msec(1000);
		//Close Claw .7 Secconds
		//Step 2: Grab cube
		StopMoving();
		motor[lift1] = 127;
		motor[lift2] = 127;
		wait1Msec(600);
		//Open Claw .4 Secconds
		TurnLeft();
		wait1Msec(900);
		//Rotate Right .7 Secconds
		MoveForward();
		wait1Msec(1300);
		//Move Forwards 1.3 Secconds
		motor[claw] = -127;
		wait1Msec(300);
		//Open Claw .3 Secconds
		//Step 4: Lift and drop cube off other side
		motor[claw] = -127;
		motor[lift1] = 0;
		motor[lift2] = 0;
		StopMoving();
		wait1Msec(600);
		//NEXT TASK: Knock rest of stars off fence
		//Stop
		motor[lift1] = 40;
		motor[lift2] = 40;
		MoveBackward();
		wait1Msec(1000);
		//Move Backwards
		//Step 1: Move back into position
		motor[lift1] = -127;
		motor[lift2] = -127;
		motor[claw] = 127;
		wait1Msec(500);
		//Move Backwards and Lower Lift
		StopMoving();
		//Move Forwards
		//Step 2: Knock stars off
		MoveForward();
		motor[claw] = 0;
		motor[lift1] = 20;
		motor[lift2] = 20;
		wait1Msec(700);
		MoveForward();
		wait1Msec(700);
		StopMoving();
		//Stop
		//NEXT TASK: Knock everything off
		MoveBackward();
		wait1Msec(1200);
		//Move Backwards and maintain lift
		TurnRight();
		wait1Msec(600);
		//Turn Left
		MoveForward();
		wait1Msec(1600);
		//Move Forwards
		TurnLeft();
		wait1Msec(600);
		MoveForward();
		wait1Msec(1200);
		StopMoving();
		//Stop


		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Right Time");
		displayLCDCenteredString(1, "is running!");
		MoveForward();
		motor[hang] = 127;
		motor[lift1] = 127;
		motor[lift2] = 127;
		wait1Msec(800);
		//Move Forward .8 Secconds
		//Step 1: Move out of starting square
		motor[lift1] = 20;
		motor[lift2] = 20;
		TurnRight();
		wait1Msec(450);
		//Rotate Right .45 Secconds
		MoveForward();
		motor[claw] = 127;
		wait1Msec(350);
		//Move Forward .35 Secconds
		TurnLeft();
		motor[claw] = 0;
		wait1Msec(450);
		//Rotate Left .45 Secconds
		//Step 2: Rotate and move into position to knock stars off fence
		StopMoving();
		motor[lift1] = 127;
		motor[lift2] = 127;
		wait1Msec(800);
		//Raise Lift and Open Claw .3 Secconds
		MoveForward();
		wait1Msec(1100);
		//Move Forward 1.3 Secconds
		//Step 3: Knock stars off of fence
		motor[lift1] = 127;
		motor[lift2] = 127;
		motor[claw] = 0;
		motor[hang] = 0;
		MoveForward();
		wait1Msec(2000);
		//NEXT TASK: Get cube to other side
		MoveBackward();
		wait1Msec(950);
		//Step 1: Move into position
		TurnLeft();
		motor[lift1] = -127;
		motor[lift2] = -127;
		wait1Msec(700);
		//Rotate Left .75 Secconds
		motor[claw] = -50;
		motor[leftbottom] = 127;
		motor[lefttop] = 127;
		motor[rightbottom] = 127;
		motor[righttop] = 127;
		wait1Msec(550);
		//Move Forwards .55 Secconds
		motor[claw] = 127;
		wait1Msec(700);
		//Close Claw .7 Secconds
		//Step 2: Grab cube
		StopMoving();
		motor[lift1] = 127;
		motor[lift2] = 127;
		wait1Msec(400);
		//Open Claw .4 Secconds
		TurnRight();
		wait1Msec(900);
		//Rotate Right .7 Secconds
		MoveForward();
		wait1Msec(1300);
		//Move Forwards 1.3 Secconds
		motor[claw] = -127;
		wait1Msec(600);
		//Open Claw .3 Secconds
		//Step 4: Lift and drop cube off other side
		motor[claw] = -127;
		motor[lift1] = 0;
		motor[lift2] = 0;
		StopMoving();
		wait1Msec(600);
		//NEXT TASK: Knock rest of stars off fence
		//Stop
		motor[lift1] = 30;
		motor[lift2] = 30;
		MoveBackward();
		wait1Msec(1300);
		//Move Backwards
		//Step 1: Move back into position
		motor[lift1] = -127;
		motor[lift2] = -127;
		motor[claw] = 90;
		wait1Msec(500);
		//Move Backwards and Lower Lift
		StopMoving();
		//Move Forwards
		//Step 2: Knock stars off
		MoveForward();
		motor[claw] = 0;
		motor[lift1] = 20;
		motor[lift2] = 20;
		wait1Msec(800);
		MoveForward();
		wait1Msec(700);
		StopMoving();
		//Stop
		//NEXT TASK: Knock everything off
		MoveBackward();
		wait1Msec(1200);
		//Move Backwards and maintain lift
		TurnLeft();
		wait1Msec(600);
		//Turn Left
		MoveForward();
		wait1Msec(1600);
		//Move Forwards
		TurnRight();
		wait1Msec(600);
		MoveForward();
		wait1Msec(1200);
		StopMoving();
		//Stop

		break;
	case 2:
		//If count = 2, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Left Encoder");
		displayLCDCenteredString(1, "is running!");


		break;

	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Right Encoder");
		displayLCDCenteredString(1, "is running!");
		SensorValue[rightencoder] = 0;
		SensorValue[leftencoder] = 0;
		while (1==1) {
			if(SensorValue[rightencoder] > 360 ){
				TurnLeft();
				if(SensorValue[leftencoder] < 720) {
					MoveForward();
					motor[lift1] = 127;
					motor[lift2] = 127;
					motor[claw] = 127;
					wait1Msec(100);
					motor[lift1] = 20;
					motor[lift2] = 20;
					wait1Msec(100);
					SensorValue[leftencoder] = 0;
					SensorValue[rightencoder] = 0;
					if(SensorValue[rightencoder] == 0){
						StopMoving();
						motor[claw] = 0;
					}
				}
			}
			if(SensorValue[rightencoder] < 359){
				MoveForward();
			}
		}

		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!!");
		MoveForward();
		break;
}
}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	int clawctrl = 0;
	int clawspeed = 0;
	int lockclaw = 0;
	// User control code here, inside the loop
	startTask(encoders);
	while(1 == 1)
	{
		//Right side of the robot is controlled by the right joystick, Y-axis
		motor[righttop] = vexRT[Ch2];
		motor[rightbottom]  = vexRT[Ch2];
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[lefttop] = vexRT[Ch3];
		motor[leftbottom]  = vexRT[Ch3];
		if(vexRT[Btn6D] == 1) {
			motor[hang] = -127;
		}
		if(vexRT[Btn6U] == 1) {
			motor[hang] = 127;
		}
		if(vexRT[Btn6D] == 0) {
			if(vexRT[Btn6U] == 0) {
				motor[hang] = 0;
			}
		}
		motor[lift1] = vexRT[Ch2Xmtr2];
		motor[lift2] = vexRT[Ch2Xmtr2];
		int reqclawspeed = vexRT[Ch3Xmtr2];
		if (reqclawspeed < clawspeed)
		{
			int diff = clawspeed - reqclawspeed;
			clawspeed -= diff > 35 ? 35 : diff;
		}
		else if (reqclawspeed > clawspeed)
			{
				int diff2 = reqclawspeed - clawspeed;
			clawspeed += diff2 > 35 ? 35 : diff2;
		}
			motor[claw]=clawspeed;
			wait1Msec(15);
		}

			//Dual Lock Loop
		if(vexRT[Btn8D] == 1){
			//Check if the claw is locked already or not
		if(lockclaw == 0){
			//If it is not locked, lock the claw
		motor[claw] = 20;
		lockclaw = 1;
				}
		if(lockclaw == 1){
			//If it already is locked, unlock the claw
			lockclaw = 0;
				}
			}
		//Claw Control with lock
		if(lockclaw == 0){
			//If claw is unlocked
		motor[claw] = vexRT[Ch3Xmtr2];
	}
		{
			bLCDBacklight = false;									// Turn on LCD Backlight
			string mainBattery, backupBattery;

			{
				clearLCDLine(0);											// Clear line 1 (0) of the LCD
				clearLCDLine(1);											// Clear line 2 (1) of the LCD
				//Display the Primary Robot battery voltage
				displayLCDString(0, 0, "Primary: ");
				sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
				displayNextLCDString(mainBattery);

				//Display the Backup battery voltage
				displayLCDString(1, 0, "Backup: ");
				sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
				displayNextLCDString(backupBattery);

				//Short delay for the LCD refresh rate
				wait1Msec(100);

				}

		}

	}
