#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           righttop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightbottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lefttop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftbottom,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                              Autonomous Task                              */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[leftbottom] = 127;
	motor[rightbottom] = 127;
	motor[righttop] = 127;
	motor[lefttop] = 127;
	wait1Msec(1000);
	//Move Forward 1 Secconds
	motor[leftbottom] = 127;
	motor[rightbottom] = -127;
	motor[righttop] = -127;
	motor[lefttop] = 127;
	wait1Msec(500);
	//Rotate Right .5 Secconds
	motor[leftbottom] = 127;
	motor[rightbottom] = 127;
	motor[righttop] = 127;
	motor[lefttop] = 127;
	wait1Msec(500);
	//Move Forward .5 Secconds
	motor[leftbottom] = -127;
	motor[rightbottom] = 127;
	motor[righttop] = 127;
	motor[lefttop] = -127;
	wait1Msec(500);
	//Rotate Left .5 Secconds
	motor[lift1] = 127;
	motor[lift2] = 127;
	motor[claw] = 127;
	wait1Msec(700);
	//Raise Lift and Open Claw .7 Secconds
	motor[leftbottom] = 127;
	motor[rightbottom] = -127;
	motor[righttop] = -127;
	motor[lefttop] = 127;
	wait1Msec(200);
	//Move Forward .2 Secconds
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                              User Control Task                            */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// Control Code Here

	while (true)
	{
		//Chasis Drive, Directly Bound to Controller
		motor(righttop)=vexRT[Ch2];
		motor(rightbottom)=vexRT[Ch2];
		motor(lefttop)=vexRT[Ch3];
		motor(leftbottom)=vexRT[Ch3];
		//Lift Drive, Directly Bound to Controller
		motor(lift1)=vexRT[Ch2Xmtr2];
		motor(lift2)=vexRT[Ch2Xmtr2];
	}
}
