#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftencoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           righttop,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightbottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lefttop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftbottom,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           hang,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//LCD Display code.
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
//Declare count variable to keep track of our choice
int count = 0;
//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

//

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////



void pre_auton()
{
	SensorValue(rightencoder) = 0;
	SensorValue(leftencoder) = 0;
	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Red Left");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Red Right");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Blue Left");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Blue Right");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:

			count = 0;

			break;

		}
	}

}
//FUNCTIONS: Convert chasis rotations to inches and vise versa for easy autonomous coding. Do this by having functions which before being
//called are given a value (inches) to move or rotate.
int inchesmoved = 0;
int inchestomove = 0;
int rightinches = 0;
int leftinches = 0;
int nextstep = 0;
int rightinchestomove = 0;
int leftinchestomove = 0;
void pre_auton()
{

}


void moveforward()
{
	while(inchesmoved < inchestomove)
	{
		motor[leftbottom] = 127;
		motor[lefttop] = 127;
		motor[rightbottom] = 127;
		motor[righttop] = 127;
	}
		motor[leftbottom] = 0;
		motor[lefttop] = 0;
		motor[rightbottom] = 0;
		motor[righttop] = 0;
		nextstep = nextstep + 1;
}

void movebackward()
{
	while(inchesmoved < inchestomove)
	{
		motor[leftbottom] = -127;
		motor[lefttop] = -127;
		motor[rightbottom] = -127;
		motor[righttop] = -127;
	}
		motor[leftbottom] = 0;
		motor[lefttop] = 0;
		motor[rightbottom] = 0;
		motor[righttop] = 0;
		nextstep = nextstep + 1;
}
void turnright()
{
	while(rightinches < rightinchestomove)
	{
		motor[leftbottom] = 127;
		motor[lefttop] = 127;
		motor[rightbottom] = -127;
		motor[righttop] = -127;
	}
		motor[leftbottom] = 0;
		motor[lefttop] = 0;
		motor[rightbottom] = 0;
		motor[righttop] = 0;
		nextstep = nextstep + 1;
}
void turnleft()
{
	while(leftinches < leftinchestomove)
	{
		motor[leftbottom] = -127;
		motor[lefttop] = -127;
		motor[rightbottom] = 127;
		motor[righttop] = 127;
	}
		motor[leftbottom] = 0;
		motor[lefttop] = 0;
		motor[rightbottom] = 0;
		motor[righttop] = 0;
		nextstep = nextstep + 1;
}

task algo()
{
	while(true)
	{
	rightinches = SensorValue[rightencoder] * 12.56 / 360;
  leftinches = SensorValue[leftencoder] * -12.56 / 360;
  inchesmoved = (leftinches + rightinches)/2;
  wait1Msec(1);
  writeDebugStreamLine("left encoder count is %d", SensorValue[leftencoder]*-1 );
  writeDebugStreamLine("right encoder count is %d", SensorValue[rightencoder]*-1 );
  writeDebugStreamLine("inches moved is %d", inchesmoved);
	}
}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	startTask (algo);
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Red Left");
		displayLCDNumber(1, 0, inchesmoved, 1);
		SensorValue[leftencoder] = 0;
		SensorValue[rightencoder] = 0;
		inchestomove = 14;
		nextstep = 1;
		while (nextstep == 1)
		{
			moveforward();
		}
		inchestomove = 0;
		rightinchestomove = 5;
		while (nextstep == 2)
		{
			turnright();
		}

		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Red Right");
		displayLCDCenteredString(1, "is running!");



		break;
	case 2:
		//If count = 2, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Blue Left");
		displayLCDCenteredString(1, "is running!");

		break;

	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Blue Right");
		displayLCDCenteredString(1, "is running!");


		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!!");
		break;
}}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	startTask (algo);
	while(1 == 1)
	{
		//Right side of the robot is controlled by the right joystick, Y-axis
		motor[righttop] = vexRT[Ch2];
		motor[rightbottom]  = vexRT[Ch2];
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[lefttop] = vexRT[Ch3];
		motor[leftbottom]  = vexRT[Ch3];
		if(vexRT[Btn6DXmtr2] == 1) {
			motor[hang] = -127;
		}
		if(vexRT[Btn6UXmtr2] == 1) {
			motor[hang] = 127;
		}
		if(vexRT[Btn6DXmtr2] == 0) {
			if(vexRT[Btn6UXmtr2] == 0) {
				motor[hang] = 0;
			}
		}
		motor[lift1] = vexRT[Ch2Xmtr2];
		motor[lift2] = vexRT[Ch2Xmtr2];
		motor[claw]= vexRT[Ch3Xmtr2];    {
			bLCDBacklight = true;									// Turn on LCD Backlight
			string mainBattery, backupBattery;

			{
				clearLCDLine(0);											// Clear line 1 (0) of the LCD
				clearLCDLine(1);											// Clear line 2 (1) of the LCD
				//Display the Primary Robot battery voltage
//				displayLCDString(0, 0, "Primary: ");
//				sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
//				displayNextLCDString(mainBattery);

//				//Display the Backup battery voltage
//				displayLCDString(1, 0, "Backup: ");
//				sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
//				displayNextLCDString(backupBattery);

				displayLCDNumber(1, 0, inchesmoved, 1);

				//Short delay for the LCD refresh rate
				wait1Msec(100);

			}
		}

	}
}
