#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftencoder,    sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           righttop,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightbottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lefttop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftbottom,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw1,         tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           claw2,         tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//LCD Display code.
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
//Declare count variable to keep track of our choice
int count = 0;
//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release----------------------------------1--------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

//

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void TurnLeft()
{
	motor[leftbottom] = -127;
	motor[rightbottom] = 127;
	motor[righttop] = 127;
	motor[lefttop] = -127;
}
void TurnRight()
{
	motor[leftbottom] = 127;
	motor[rightbottom] = -127;
	motor[righttop] = -127;
	motor[lefttop] = 127;
}
void MoveForward()
{
	motor[leftbottom] = 127;
	motor[rightbottom] = 127;
	motor[righttop] = 127;
	motor[lefttop] = 127;
}
void MoveBackward()
{
	motor[leftbottom] = -127;
	motor[rightbottom] = -127;
	motor[righttop] = -127;
	motor[lefttop] = -127;
}
void StopMoving()
{
	motor[leftbottom] = 0;
	motor[rightbottom] = 0;
	motor[righttop] = 0;
	motor[lefttop] = 0;
}
void pre_auton()
{

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Left Time");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Right Time");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Left Encoders");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Right Encoders");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:

			count = 0;

			break;

		}
	}

}
task encoders(){
	SensorValue(rightencoder) = 0;
	SensorValue(leftencoder) = 0;
	int rightencoder = SensorValue(rightencoder);
	int leftencoder = SensorValue(leftencoder);
	while (1){
	rightencoder = SensorValue(rightencoder);
	leftencoder = SensorValue(leftencoder);
}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	startTask(encoders);
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Left Time");
		displayLCDCenteredString(1, "is running!");

		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Right Time");
		displayLCDCenteredString(1, "is running!");

		break;
	case 2:
		//If count = 2, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Left Encoder");
		displayLCDCenteredString(1, "is running!");


		break;

	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Right Encoder");
		displayLCDCenteredString(1, "is running!");

		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!!");
		MoveForward();
		break;
}
}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	startTask(encoders);
	while(1 == 1)
	{
		//Right side of the robot is controlled by the right joystick, Y-axis
		motor[righttop] = vexRT[Ch2];
		motor[rightbottom]  = vexRT[Ch2];
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[lefttop] = vexRT[Ch3];
		motor[leftbottom]  = vexRT[Ch3];

		motor[lift1] = vexRT[Ch2Xmtr2];
		motor[lift2] = vexRT[Ch2Xmtr2];
		motor[claw1] = vexRT[Ch2Xmtr2];
	}
		{
			bLCDBacklight = false;									// Turn on LCD Backlight
			string mainBattery, backupBattery;

			{
				clearLCDLine(0);											// Clear line 1 (0) of the LCD
				clearLCDLine(1);											// Clear line 2 (1) of the LCD
				//Display the Primary Robot battery voltage
				displayLCDString(0, 0, "Primary: ");
				sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
				displayNextLCDString(mainBattery);

				//Display the Backup battery voltage
				displayLCDString(1, 0, "Backup: ");
				sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
				displayNextLCDString(backupBattery);

				//Short delay for the LCD refresh rate
				wait1Msec(100);

				}

		}

	}
