#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           catapult1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapult2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift2,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//- The left joystick Y-axis controls the robot's forward and backward movement.
//- The left joystick X-axis controls the robot's left and right movement.
//- The right joystick X-axis controls the robot's rotation.
//- This program incorportes a threshold/deadzone that allows very low Joystick values to be ignored.
//                                 Preauton Task
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
}

//                                 Autonomous Task

task autonomous()
{

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}
//                                 User Control Task
task usercontrol()
{
	//Deadzone variables. Adjust threshold value to increase/decrease deadzone
	int catapultspeed;
	int liftspeed;
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;


	while(1 == 1)
	{
		//deadzone for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//deadzone for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//deadzone for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;
		//Lift
		if(vexRT[Btn5U] == 1){
			liftspeed = 127;
		}
		if(vexRT[Btn5D] == 1){
			liftspeed = -127;
		}
		if(vexRT[Btn5DXmtr2] == 0){
			if(vexRT[Btn5UXmtr2] == 0){
				liftspeed = 0;
			}
		}
		//Catapult
		if(vexRT[Btn6U] == 1){
			catapultspeed = 127;
		}
		if(vexRT[Btn6D] == 1){
			catapultspeed = -127;
		}
		if(vexRT[Btn6DXmtr2] == 0){
			if(vexRT[Btn6UXmtr2] == 0){
				liftspeed = 0;
			}
		}
		//Control
		motor[lift1] = liftspeed;
		motor[lift2] = liftspeed;
		motor[catapult1] = catapultspeed;
		motor[catapult2] = catapultspeed;
		motor[frontRight] = Y1 - X2 - X1;
		motor[backRight] =  Y1 - X2 + X1;
		motor[frontLeft] = Y1 + X2 + X1;
		motor[backLeft] =  Y1 + X2 - X1;
	}
}
