#pragma config(Motor,  motor2,          TopLeft,       tmotorVexIQ, openLoop)
#pragma config(Motor,  motor3,          BottomLeft,    tmotorVexIQ, openLoop)
#pragma config(Motor,  motor4,          TopRight,      tmotorVexIQ, openLoop)
#pragma config(Motor,  motor5,          BottomRight,   tmotorVexIQ, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)



task main()
{
	// User control code here, inside the loop

	while (true)
	{
		if(vexRT[Btn8R] == 1)
		{
			motor[TopLeft] = 100;
			motor[BottomLeft] = -100;
			motor[TopRight] = 100;
			motor[BottomRight] = -100;
		}
			if(vexRT[Btn8U] == 0)
		{
			motor[TopLeft] = 0;
			motor[BottomLeft] = 0;
			motor[TopRight] = 0;
			motor[BottomRight] = 0;
		}
		if(vexRT[Btn8D] == 1)
		{
			motor[TopLeft] = 100;
			motor[BottomLeft] = 100;
			motor[TopRight] = -100;
			motor[BottomRight] = -100;
		}
		if(vexRT[Btn8U] == 1)
		{
			motor[TopLeft] = -100;
			motor[BottomLeft] = -100;
			motor[TopRight] = 100;
			motor[BottomRight] = 100;
		}
			if(vexRT[Btn8L] == 1)
		{
			motor[TopLeft] = -100;
			motor[BottomLeft] = 100;
			motor[TopRight] = -100;
			motor[BottomRight] = 100;
		}
			if(vexRT[Btn5U] == 1)
		{
			motor[TopLeft] = 100;
			motor[BottomLeft] = -100;
			motor[TopRight] = -100;
			motor[BottomRight] = 100;
		}
			if(vexRT[Btn6U] == 1)
		{
			motor[TopLeft] = -100;
			motor[BottomLeft] = 100;
			motor[TopRight] = 100;
			motor[BottomRight] = -100;
		}
	}
}
