#pragma config(Motor,  port2,           RightTrack,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftTrack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FrontTrack,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BackTrack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait(5);
	motor[LeftTrack] = 100;
	motor[RightTrack] = 100;
	wait(2
	);
	while(1 == 1)
	{
		motor[RightTrack] = vexRT[Ch2];
		motor[LeftTrack] = vexRT[Ch2];
		motor[FrontTrack] = vexRT[Ch3];
		motor[BackTrack] = vexRT[Ch3];
			if(vexRT[Btn6D] == 1)
		{
			motor[LeftTrack] = 100;
			motor[FrontTrack] = 100;
			motor[BackTrack] = 100;
		}
			if(vexRT[Btn5D] == 1)
		{
			motor[RightTrack] = 100;
			motor[FrontTrack] = 100;
			motor[BackTrack] = 100;
		}
			if(vexRT[Btn6U] == 1)
		{
			motor[LeftTrack] = 100;
			motor[FrontTrack] = 100;
			motor[BackTrack] = -100;
			motor[RightTrack] = -100;
		}
			if(vexRT[Btn8U] == 1)
		{
			motor[port6] = 100;
		}
			if(vexRT[Btn8D] == 1)
		{
			motor[port6] = -100;
		}
			if(vexRT[Btn5U] == 1)
		{
			motor[LeftTrack] = -100;
			motor[FrontTrack] = -100;
			motor[BackTrack] = 100;
			motor[RightTrack] = 100;
		}
	}
}
