#pragma config(Motor,  port2,           L1,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           L2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           R1,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           R2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           S1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           S2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           S3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           S4,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1)
	{
		motor[L1] = vexRT[Ch2];
		motor[L2] = vexRT[Ch2];
		motor[R1] = vexRT[Ch3];
		motor[R2] = vexRT[Ch3];
		motor[S1] = vexRT[Ch2Xmtr2];
		motor[S2] = vexRT[Ch2Xmtr2];
		motor[S3] = vexRT[Ch3Xmtr2];
		motor[S4] = vexRT[Ch3Xmtr2];
		if(vexRT[Btn6U] == 1)
		{
			motor[LeftTrack] = 100;
			motor[FrontTrack] = -100;
			motor[BackTrack] = 100;
			motor[RightTrack] = -100;
		}
		if(vexRT[Btn5U] == 1)
		{
			motor[LeftTrack] = -100;
			motor[FrontTrack] = 100;
			motor[BackTrack] = -100;
			motor[RightTrack] = 100;
		}
	}
}
